### PR TITLE
BUG/MINOR: update predicate in controller registration

### LINKED ISSUE #11: Backend not populated for "secondary ports"
At trying to use `TLSRoutes`, I experience the following (cannot tell if it's the case for HTTP/HTTPS routes as well): backend ends up being populated by pod endpoints only for the service "primary port". Others aren't.

I'm using the latest v0.8 and [Gateway-API 1.3.0 from experimental channel](https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml).

## k8s setup

The service:
```
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: myns
(...)
spec:
  clusterIP: 100.96.247.198
  clusterIPs:
  - 100.96.247.198
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    port: 31443
    protocol: TCP 
    targetPort: 31443
  - name: admin
    port: 32132
    protocol: TCP 
    targetPort: 32132
  sessionAffinity: None
  type: ClusterIP
```

The gateway:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mygateway
  namespace: myns
(...)
spec:
  gatewayClassName: haproxy
  listeners:
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TLSRoute
      namespaces:
        from: All 
    hostname: '*.subdomain.example.tld'
    name: api
    port: 31443
    protocol: TLS 
    tls:
      mode: Passthrough
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TLSRoute
      namespaces:
        from: All
    hostname: '*.subdomain.example.tld'
    name: admin
    port: 32132
    protocol: TLS
    tls:
      mode: Passthrough
```

TL;DR: 
* pod and serviceport are kept aligned for simplicity
* GW goal is to perform SNI routing using multiple ports in parallel and use the same naming pattern for both of them.

The TLSRoutes (both ending up with "accepted" and "refs resolved" statuses)
```
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: demo-api
  namespace: myns
spec:
  hostnames:
  - demo.subdomain.example.tld
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: mygateway
    sectionName: api
  rules:
  - backendRefs:
    - kind: Service
      name: demo
      namespace: myns
      port: 31443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: demo-admin
  namespace: myns
spec:
  hostnames:
  - demo.subdomain.example.tld
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: mygateway
    sectionName: admin
  rules:
  - backendRefs:
    - kind: Service
      name: demo
      namespace: myns
      port: 32123
```

## What is happening in terms of haproxy config generated

Good from a map perspective:
```
/ $ cat /usr/local/hug/maps/link1_myns_mygateway_api/sni.map 
demo.subdomain.example.tld link1_myns_demo_31443_
/ $ cat /usr/local/hug/maps/link1_myns_mygateway_admin/sni.map 
demo.subdomain.example.tld link1_myns_demo_32123_
```

2 frontends created, as expected:
```
frontend link1_myns_mygateway_api from haproxytech # {"hug":{"Gateway":{"myns/mygateway":{"Generation":3,"LinkID":"link1"}}}}
  bind 0.0.0.0:31443 name v4
  bind [::]:31443 name v6
  acl route_is_json var(txn.sni_match),bytes(0,1) -m str { # {"hug":"for lua routing"}
  tcp-request content reject if !{ req_ssl_hello_type 1 }
  tcp-request inspect-delay 50000
  tcp-request content set-var(sess.sni) req_ssl_sni
  tcp-request content set-var(txn.sni_match) req_ssl_sni,map(/usr/local/hug/maps/link1_myns_mygateway_api/sni.map)
  tcp-request content set-var(txn.sni_match,ifnotexists) req_ssl_sni,map_end(/usr/local/hug/maps/link1_myns_mygateway_api/domain_wildcard_sni.map)
  use_backend %[var(txn.backend)] if route_is_json
  use_backend %[var(txn.sni_match),field(1,.)]
  default_backend backend_not_found

frontend link1_myns_mygateway_admin from haproxytech # {"hug":{"Gateway":{"myns/mygateway":{"Generation":3,"LinkID":"link1"}}}}
  bind 0.0.0.0:32132 name v4
  bind [::]:32132 name v6
  acl route_is_json var(txn.sni_match),bytes(0,1) -m str { # {"hug":"for lua routing"}
  tcp-request content reject if !{ req_ssl_hello_type 1 }
  tcp-request inspect-delay 50000
  tcp-request content set-var(sess.sni) req_ssl_sni
  tcp-request content set-var(txn.sni_match) req_ssl_sni,map(/usr/local/hug/maps/link1_myns_mygateway_admin/sni.map)
  tcp-request content set-var(txn.sni_match,ifnotexists) req_ssl_sni,map_end(/usr/local/hug/maps/link1_myns_mygateway_admin/domain_wildcard_sni.map)
  use_backend %[var(txn.backend)] if route_is_json
  use_backend %[var(txn.sni_match),field(1,.)]
  default_backend backend_not_found

frontend stats from haproxytech
  mode http
(...)
```

But only the first backend is populated:
```
backend link1_myns_demo_31443_ from haproxytech # {"hug":{"TLSRoute":{"myns/demo-api":{"Generation":1,"LinkID":"link1"}}}}
  mode tcp
  balance roundrobin
  no option abortonclose
  timeout server 50000
  default-server check
  server SRV_be7b0b8857b1071a4f722ea99a4f5d35ae59a49e 10.1.1.143:31443 enabled
  server SRV_2662e3a8dd72c6efba2679b05fbea54cbcb69ced 10.1.1.185:31443 enabled
  server SRV_3aedbf82d4f03fce6c7b406696f380f0845c1310 10.1.1.132:31443 enabled

backend link1_myns_demo_32123_ from haproxytech # {"hug":{"TLSRoute":{"myns/demo-admin":{"Generation":1,"LinkID":"link1"}}}}
  mode tcp
  balance roundrobin
  no option abortonclose
  timeout server 50000
  default-server check
```

Sorry for not providing a ready-to-use reproducer, I think only minor adaptations from what I provided should allow to replay the scenario.

### PR DESCRIPTION
**Pull request by pierrecdn**
Replaced `GenerationChangedPredicate` with `ResourceVersionChangedPredicate` in the controller registration logic to improve resource tracking, since I observed cases where services targeting multiple ports were left empty of servers for the [2..N] backends/ports until next batch.

Fixes #11

### CODE REVIEW

File: k8s/gate/controller.go [hunk 1]
```diff
@@ -372,7 +372,7 @@ func registerControllers(ctx context.Context, extractGVK utilsk8s.ExtractGVK, cf
 			options: []Option{
 				WithK8sPredicate(
 					k8spredicate.And(
-						k8spredicate.GenerationChangedPredicate{},
+						k8spredicate.ResourceVersionChangedPredicate{},
```
Comment (hdurand0710) [inline k8s/gate/controller.go:375]: Are you sure that this will fix the issue that you mentionned?
If I'm not wrong, the difference between GenerationChanged and ResourceVersionChanged is as as following:
- GenerationChanged is triggered for changes on the spec only
- ResourceVersion is triggered for changed on the spec  + status + metadata (annotations...)
How would the status or annotations changes impact the backends ? 
I would prefer to keep the GenerationChanged to not be triggered by status changes.
Your issue might be the sign of a bug more deep somewhere that needs to be investigated.

I realized that we were not synchronizing the part were we were computing the config diffs (the gate part) and the hug part were we apply the configuration, which was fine until we added runtime command in the gate part. This needs to be done sequentially.
I will add a MR to fix that and synchronize these goroutines. 
I don't think this will fix your issue though...

Comment (pierrecdn) [reply k8s/gate/controller.go:375]: I did rebuild and deploy, I can tell that now each time I'm getting my 2 backends populated.
Before, the 2nd one stayed empty of server until I forced a container restart.

Indeed the root cause may be deeper, but at least I can tell that one solves (might give a clue on the root cause?).

Comment (pierrecdn) [reply k8s/gate/controller.go:375]: I guess what may be missing in my first explanation, because I did not observe it at that time :cry:, is that the service is updated over time, and a subsequent spec update adds the second port.

That's probably why ResourceVersionChanged fixes in the end.

**Comment by hdurand0710** [comment]
ok then LGTM !
Thanks a lot for your contribution.
I take it as a workaround, as it forces a resync... I have an idea for the root cause, and will see and test.
As for now, let's for for it.
